### ISSUE TITLE
Walking teleoperation fails to compile when HumanDynamicsEstimation is compiled without Xsens

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/walking-teleoperation#39]
I tried to compile the ``robotology-superbuild`` with both the options ``ROBOTOLOGY_ENABLE_HUMAN_DYNAMICS`` and ``ROBOTOLOGY_ENABLE_TELEOPERATION`` selected, ``walking-teleoperation`` fails to compile on Windows with the error:
```
1>------ Skipped Build: Project: UNINSTALL, Configuration: Release x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: XsensRetargetingModule, Configuration: Release x64 ------
2>LINK : fatal error LNK1104: cannot open file 'HumanDynamicsEstimation::HumanStateMsg-NOTFOUND.obj'
2>Done building project "XsensRetargetingModule.vcxproj" -- FAILED.
3>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 6 up-to-date, 2 skipped ==========
```

Note that we did not enable the ``ROBOTOLOGY_USES_XSENS_MVN_SDK `` option. 

cc @kouroshD @GiulioRomualdi

**Comment by traversaro** [comment]
Sorry, I just realized that this is not tested in the superbuild. I added it in https://github.com/robotology/robotology-superbuild/pull/460 .

**Comment by traversaro** [comment]
@GiulioRomualdi just to understand, this was solved for running the Oculus demo or it was not necessary?

**Comment by traversaro** [comment]
Friendly ping @S-Dafarra @kouroshD @GiulioRomualdi , "we are not working on this" is also an acceptable answer. : )

**Comment by S-Dafarra** [comment]
> @GiulioRomualdi just to understand, this was solved for running the Oculus demo or it was not necessary?

We simply disabled ``ROBOTOLOGY_ENABLE_HUMAN_DYNAMICS`` and tested without it. Nonetheless, the problem remains. @kouroshD any hint?

**Comment by GiulioRomualdi** [comment]
I completely miss the comments I'm sorry. As far as I understood we disable the compilation of the repo in the windows laptop. Right now I'm not working on this. I don't know about the others

**Comment by traversaro** [comment]
Ok, thanks!

**Comment by traversaro** [comment]
Just to understand, how did the recent demos work if this is still unsolved?

**Comment by S-Dafarra** [comment]
>Just to understand, how did the recent demos work if this is still unsolved?

I were keeping the ``ROBOTOLOGY_ENABLE_HUMAN_DYNAMICS`` option to OFF and we enable it as soon as we had the XSens SDK available.

**Comment by kouroshD** [comment]
When I try the Generate the solution for that, I see the following error as well on CMake Gui application:
```
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_IMPLIB not set for imported target
  "HumanDynamicsEstimation::HumanStateMsg" configuration "Debug".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_IMPLIB not set for imported target
  "HumanDynamicsEstimation::HumanStateMsg" configuration "Release".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_IMPLIB not set for imported target
  "HumanDynamicsEstimation::HumanStateMsg" configuration "MinSizeRel".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_IMPLIB not set for imported target
  "HumanDynamicsEstimation::HumanStateMsg" configuration "RelWithDebInfo".
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Moreover, as you mentioned before, when building we have the following linking problem:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'HumanDynamicsEstimation::HumanStateMsg-NOTFOUND.obj'	XsensRetargetingModule	C:\Users\kdarvish\robotology-superbuild\build\src\walking-teleoperation\modules\Xsens_module\LINK	1	
```

So, What I thought to check as the first step was if the target for the `HumanDynamicsEstimation::HumanStateMsg` is built or not. To do so, I checked the installed folders, and this is the result:
- on the `install/lib` we do not have it.
- we have `install/bin/HumanStateMsg.dll`

Also, talking with @S-Dafarra, I have deleted the `SHARED` option in https://github.com/robotology/human-dynamics-estimation/blob/a55ee0d28373a1632f29667435fdd1f770eefce0/msgs/yarp/thrift/CMakeLists.txt#L18 and https://github.com/robotology/human-dynamics-estimation/blob/a55ee0d28373a1632f29667435fdd1f770eefce0/msgs/yarp/thrift/CMakeLists.txt#L56. By deleting them, we allow the CMake to build the library with the default value of `BUILD_SHARED_LIBS`.
So, that as now, we have `install/bin/HumanStateMsg.lib` file and the Walking teleoperation can build successfully when the `XsensRetargeting` module is enabled.  It tried to build HDE and Walking teleoperation, and they are built successfully.

**Comment by traversaro** [comment]
Probably the reason is that `HumanStateMsg` did not exported windows symbols. The alternative is to build it as static as you did, or set to on in hde https://cmake.org/cmake/help/v3.4/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html .

**Comment by kouroshD** [comment]
Probably with this fix, we can add the github actions of the walking teleoperation to the superbuild, also enabling the related module option.

**Comment by traversaro** [comment]
> 
> 
> Probably with this fix, we can add the github actions of the walking teleoperation to the superbuild, also enabling the related module option.

For reference, you need to modify the if in  https://github.com/robotology/robotology-superbuild/blob/master/.ci/initial-cache.gh.cmake#L23 . Related issue: https://github.com/robotology/robotology-superbuild/issues/472 .

**Comment by S-Dafarra** [comment]
> Probably the reason is that `HumanStateMsg` did not exported windows symbols. The alternative is to build it as static as you did, or set to on in hde https://cmake.org/cmake/help/v3.4/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html .

Example of usage https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L45-L48

**Comment by traversaro** [comment]
Not sure what changed, but I re-enabled the compilation of walking-teleoperation on Windows in https://github.com/robotology/robotology-superbuild/pull/1115 and it is working fine.
